FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/halfmoon /usr/local/bin/halfmoon
COPY $TARGETPLATFORM/halfmoon-launcher /usr/local/bin/halfmoon-launcher
COPY $TARGETPLATFORM/halfmoon-launcher-tui /usr/local/bin/halfmoon-launcher-tui

ENTRYPOINT ["halfmoon-launcher"]
CMD ["-console", "-public", "-no-browser"]
